name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/richwasm/iris-richwasm-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      # we can run as root since `OPAMROOT` and `OPAMROOTISOK` are baked into the image
      options: --user root
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: _build
          key: dune-v1-${{ hashFiles('dune-project', 'iris-richwasm.opam') }}-${{ github.sha }}
          restore-keys: |
            dune-v1-${{ hashFiles('dune-project', 'iris-richwasm.opam') }}-
      - name: Build
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          opam install . --deps-only --confirm-level=unsafe-yes -j $(nproc)
          opam exec -- dune build -p iris-richwasm -j $(nproc) @install
